services:
  bringaterv:
    image: ghcr.io/czdanika/bringaterv:latest
    ports:
      - "${PORT:-8088}:80"
    environment:
      LOGIN_ENABLED: ${LOGIN_ENABLED:-true}
      LOGIN_USER: ${LOGIN_USER:-bringa}
      LOGIN_PASSWORD: ${LOGIN_PASSWORD:-terv}
    restart: unless-stopped
